"""add_user_role_field

Revision ID: 6a5febe4cf83
Revises: 0317cbf399f5
Create Date: 2026-04-02 14:11:19.472876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6a5febe4cf83"
down_revision: Union[str, None] = "0317cbf399f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users", sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.execute("UPDATE users SET role = 'applicant' WHERE role IS NULL")
    op.alter_column("users", "role", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
